enum MessageType {
  REQUEST_LATEST_BLOCK,
  RECEIVE_LATEST_BLOCK,
  REQUEST_BLOCKCHAIN,
  RECEIVE_BLOCKCHAIN,
  REQUEST_TRANSACTIONS,
  RECEIVE_LATEST_TRANSACTION,
  RECEIVE_TRANSACTIONS,
  RECEIVE_REMOVE_TRANSACTION
}

export default MessageType;